version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:7.0.5
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 1m30s
      timeout: 10s
      retries: 2
      start_period: 30s


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.12-management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD" ,"wget", "http://localhost:7474"]
      interval: 1m30s
      timeout: 10s
      retries: 2
      start_period: 30s

  # telegram:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: development
  #   command: nest start telegram
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/usr/src/app
  #     - ./node_modules:/usr/src/app/node_modules
  #   depends_on:
  #     # neo4j:
  #       # condition: service_healthy
  #     rabbitmq: 
  #       condition: service_healthy

  