version: '3.9'

services:
  # neo4j:
  #   image: neo4j:5.9.0
  #   restart: unless-stopped
  #   environment:
  #     - NEO4J_server.memory.heap.initial_size=1G
  #     - NEO4J_server.memory.heap.max_size=2G
  #     - NEO4J_PLUGINS=["apoc", "graph-data-science"]
  #     - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
  #     - NEO4J_AUTH=neo4j/password
  #   healthcheck:
  #     test: ['CMD', 'wget', 'http://localhost:7474']
  #     interval: 10s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 10s
  #   ports:
  #     - 7687:7687

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.12-management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD" ,"wget", "http://localhost:7474"]
      interval: 1m30s
      timeout: 10s
      retries: 2
      start_period: 40s

  telegram:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: nest start telegram
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    depends_on:
      # neo4j:
        # condition: service_healthy
      rabbitmq: 
        condition: service_healthy

  